<a href="https://colab.research.google.com/github/Deekshitmanisai/Deekshit-s-DataBase/blob/main/Preprocessing_Q4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

M = 4
N = 5

matrix = np.array([
    [1.2, 3.5, 5.7, 2.1, 4.4],
    [6.8, 2.4, 3.6, 8.7, 5.9],
    [4.3, 7.1, 8.2, 1.4, 3.7],
    [9.8, 2.1, 4.5, 6.2, 7.0]
])

In [2]:
matrix_T = matrix.T

In [3]:
covariance_matrix = np.cov(matrix_T, rowvar=False)

In [4]:
correlation_matrix = np.corrcoef(matrix_T, rowvar=False)

In [5]:
print(f'Matrix (MxN dimension):\n{matrix}\n')
print(f'Covariance Matrix (MxM dimension):\n{covariance_matrix}\n')
print(f'Correlation Matrix (MxM dimension):\n{correlation_matrix}\n')


Matrix (MxN dimension):
[[1.2 3.5 5.7 2.1 4.4]
 [6.8 2.4 3.6 8.7 5.9]
 [4.3 7.1 8.2 1.4 3.7]
 [9.8 2.1 4.5 6.2 7. ]]

Covariance Matrix (MxM dimension):
[[ 3.207  -2.8255  3.121  -2.867 ]
 [-2.8255  6.327  -6.3865  5.228 ]
 [ 3.121  -6.3865  7.443  -4.4235]
 [-2.867   5.228  -4.4235  8.227 ]]

Correlation Matrix (MxM dimension):
[[ 1.         -0.62725902  0.6388079  -0.5581584 ]
 [-0.62725902  1.         -0.93065773  0.72462934]
 [ 0.6388079  -0.93065773  1.         -0.56528996]
 [-0.5581584   0.72462934 -0.56528996  1.        ]]

